# Generated by Django 3.0.7 on 2020-07-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
